### ISSUE TITLE
Support &mut [u8] for transforms

### ISSUE THREAD

**Issue by sophie-h** [pornel/rust-lcms2#12]
If I understand the library correctly, only formats of the form `[[u8,u8,u8]]` etc., are supported for RGB values.

I currently have 27 different memory layouts in my image library with formats like RGBA_16. Internally, all image data are just `[u8]`. It would be quite a hassle to transmute them all into specific rust types for all 27 memory layouts. Would it be possible to let `transform_in_place` also support `[u8]`? It should still be possible to check if the buffer length is aligned with the pixel format.

**Comment by kornelski** [comment]
Thanks for the suggestion. I've added an exception for `[u8]` slices.
