### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by kalev** [pornel/rust-lcms2#14]
Cargo.toml says that the license of the project is MIT, but there is no corresponding license file with the license text. Could you add one, please?

The MIT license is one of the licenses that requires redistributed sources to contain a copy of the license text ("The above copyright notice and this permission notice (including the next paragraph) shall be included in all copies or substantial portions of the Software.")

For reference, I'm packaging rust-lcms2 for Fedora and one of the requirements is that for licenses that contain a clause like above we need to include the full license text.

**Comment by kornelski** [comment]
Added. There's also `COPYING` in the lcms2-sys crate.

**Comment by kalev** [comment]
Excellent, thank you! lcms2-sys has COPYING, but it's not included in the crate - I opened https://github.com/kornelski/rust-lcms2-sys/pull/3 which should fix this.
