### ISSUE TITLE
Transform doesn't implement Sync

### ISSUE THREAD

**Issue by lilith** [pornel/rust-lcms2#2]
From the lcms mailing lists I thought that Transform and Profile could be used from multiple threads. Is there a reason Transform doesn't implement Sync?

**Comment by kornelski** [comment]
Transform is not safe to access from multiple threads, because it has an internal unsynchronized cache.

It is `Send` though, if you use `new_*_context()` functions that give it own non-global context.

**Comment by kornelski** [comment]
Actually, it could. I've added Flags::NO_CACHE that makes it `Sync` in e0bd98cdd1b1269848bfde92ec098d22fc0a8a32. Let me know if that works for you.

**Comment by lilith** [comment]
Wow, thanks! I recently profiled Imageflow on 1MP Adobe RGB images - 41% of time was on color transform - most of that time was creating profiles and transforms. Only 14% (of total time) was on applying the transform. Cache time!

**Comment by lilith** [comment]
Hashing the binary representation of profiles (excluding the first 80 bytes - the header) seems to work decently well as a key.  

Marti Maria suggested that approach on the mailing list, but I'm slightly concerned that some of these fields could affect transforms.

```c
// ----------------------------------------------------------------------------------------------
// ICC profile internal base types. Strictly, shouldn't be declared in this header, but maybe
// somebody want to use this info for accessing profile header directly, so here it is.

// Profile header -- it is 32-bit aligned, so no issues are expected on alignment
typedef struct {
    cmsUInt32Number              size;           // Profile size in bytes
    cmsSignature                 cmmId;          // CMM for this profile
    cmsUInt32Number              version;        // Format version number
    cmsProfileClassSignature     deviceClass;    // Type of profile
    cmsColorSpaceSignature       colorSpace;     // Color space of data
    cmsColorSpaceSignature       pcs;            // PCS, XYZ or Lab only
    cmsDateTimeNumber            date;           // Date profile was created
    cmsSignature                 magic;          // Magic Number to identify an ICC profile
    cmsPlatformSignature         platform;       // Primary Platform
    cmsUInt32Number              flags;          // Various bit settings
    cmsSignature                 manufacturer;   // Device manufacturer
    cmsUInt32Number              model;          // Device model number
    cmsUInt64Number              attributes;     // Device attributes
    cmsUInt32Number              renderingIntent;// Rendering intent
    cmsEncodedXYZNumber          illuminant;     // Profile illuminant
    cmsSignature                 creator;        // Profile creator
    cmsProfileID                 profileID;      // Profile ID using MD5
    cmsInt8Number                reserved[28];   // Reserved for future use

} cmsICCHeader;
```

**Comment by lilith** [comment]
Transform caching is implemented in the latest release of Imageflow! Thank you very much!

You mentioned Imageflow might come in handy for one of your projects. Do you have any relevant criteria/specifications or test suites? With 1.0rc out I have a little more time to work on non-critical enhancements, and I'd like to work towards making it useful for you.

**Comment by kornelski** [comment]
*Profile* creation shouldn't take much time. From littleCMS code it looks like the functions do just basic parsing of the structure, no computation. It's transform creation that's heavy, because it builds lookup tables.

With a parsed profile, you could properly extract relevant properties (white point, chromaticity, transfer function) for the cache key to cache transforms. 

With profiles I also cheat a little and check the description field. If it says it's sRGB, I believe it and take pixels as-is :)

**Comment by lilith** [comment]
Huh. Profile creation was showing up as pretty significant in the profiling. I'm going to look into that more.
