### ISSUE TITLE
MHC2 support

### ISSUE THREAD

**Issue by vaisest** [pornel/rust-lcms2#20]
I was unable to find how to write MHC2 tags. It seems that while the tag signature `lcms2::TagSignature::MHC2Tag` exists, there is no tag type associated with it. If I'm not just doing something wrong and the support isn't there, is it planned?

**Comment by kornelski** [comment]
Do you know how to do that using LCMS2 C API? I don't know if it's not supported or not exposed in the Rust wrapper.

**Comment by vaisest** [comment]
I have never tried LCMS2 with C, but it's just like any other tag as far as I can tell? [It seems like it's supported in lcms2-sys](https://github.com/kornelski/rust-lcms2-sys/blob/cb058ebbf2603e9e17cf37b0be3fc189db415716/src/ffi.rs#L1498)? However I didn't understand how to use that type with the `icc.write_tag()` method and it doesn't seem to be mentioned otherwise in this wrapper.

**Comment by kornelski** [comment]
Ah, it's a new addition, and needed update of the wrapper. Added in a741224
