### ISSUE TITLE
Double-precision `PixelFormat` values report incorrect bytes per channel

### ISSUE THREAD

**Issue by KiloJuliett** [pornel/rust-lcms2#3]
`PixelFormat::bytes_per_channel` incorrectly returns a size of 0 instead of the expected 8 if the pixel format is one of the double-precision pixel format constants (`XYZ_DBL`, `Lab_DBL`, `GRAY_DBL`, `RGB_DBL`, `BGR_DBL`, and `CMYK_DBL`).

This problem occurs in lcms2 version 5.3.0-alpha and 5.2.0. I am running Windows 1809 and compiling with stable Rust MSVC 1.44.0.

Example code:

```rust
use lcms2::PixelFormat;

fn main() {
    println!("{}", PixelFormat::XYZ_DBL.bytes_per_channel());
    println!("{}", PixelFormat::Lab_DBL.bytes_per_channel());
    println!("{}", PixelFormat::GRAY_DBL.bytes_per_channel());
    println!("{}", PixelFormat::RGB_DBL.bytes_per_channel());
    println!("{}", PixelFormat::BGR_DBL.bytes_per_channel());
    println!("{}", PixelFormat::CMYK_DBL.bytes_per_channel());
}
```

I expect the code above to output:
```
8
8
8
8
8
8
```

But instead the result is:
```
0
0
0
0
0
0
```

**Comment by kornelski** [comment]
That's inherited from upstream: 

https://github.com/mm2/Little-CMS/blob/master/include/lcms2.h#L925

**Comment by kornelski** [comment]
Fixed
